package com.example.util.localization

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    ENGLISH("en", "English", "EN"),
    RUSSIAN("ru", "Русский", "RU"),
    UZBEK("uz", "O'zbekcha", "UZ");

    companion object {
        fun fromCode(code: String): AppLanguage =
            values().find { it.code.equals(code, ignoreCase = true) } ?: ENGLISH
    }
}

data class AppStrings(
    val appTitle: String,
    val tabRequest: String,
    val tabCollections: String,
    val tabEnvironments: String,
    val tabHistory: String,
    val tabStatus: String,
    
    // Request Builder
    val noEnvironment: String,
    val save: String,
    val send: String,
    val paramsTab: String,
    val headersTab: String,
    val bodyTab: String,
    val authTab: String,
    val prettify: String,
    val noBody: String,
    val timeLabel: String,
    val sizeLabel: String,
    val snapshot: String,
    val connectionFailed: String,
    val saveRequestTitle: String,
    val requestNameLabel: String,
    val saveToCollection: String,
    val cancel: String,
    val snapshotTitle: String,
    val snapshotSubtitle: String,
    
    // Collections
    val collectionsTitle: String,
    val importPostman: String,
    val exportPostman: String,
    val newCollection: String,
    val noCollections: String,
    val noCollectionsSubtitle: String,
    val collectionNameLabel: String,
    val collectionDescLabel: String,
    val create: String,
    val loadSamplePostman: String,
    val importBtn: String,
    val copied: String,
    val copyJson: String,
    val close: String,
    
    // Environments
    val vaultUnlocked: String,
    val vaultProtected: String,
    val vaultVisibleNotice: String,
    val vaultLockedNotice: String,
    val lock: String,
    val unlock: String,
    val selectActiveEnv: String,
    val envVariablesTitle: String,
    val envUsageNotice: String,
    val newEnvironmentTitle: String,
    val envNameLabel: String,
    val authenticate: String,
    val masterPinLabel: String,
    val bioPrompt: String,
    
    // History & Compare
    val requestHistoryTab: String,
    val compareTab: String,
    val recentExecutions: String,
    val clearAll: String,
    val noHistory: String,
    val noHistorySubtitle: String,
    val openInBuilder: String,
    val setCompareA: String,
    val setCompareB: String,
    val slotA: String,
    val slotB: String,
    val diffOverview: String,
    val statusCode: String,
    val latencyDelta: String,
    val payloadDelta: String,
    val responsePayloads: String,
    val baselineOutput: String,
    val targetOutput: String,
    val compareHint: String,
    
    // Health Monitor
    val statusPageTitle: String,
    val allOperational: String,
    val endpointsOperational: String,
    val pingAll: String,
    val noMonitored: String,
    val noMonitoredSubtitle: String,
    val addEndpointTitle: String,
    val serviceNameLabel: String,
    val healthCheckUrlLabel: String,
    val expectedStatusLabel: String,
    val addEndpointBtn: String,
    
    // Theme & Lang
    val themeDark: String,
    val themeLight: String,
    val language: String
)

val EnglishStrings = AppStrings(
    appTitle = "API Playground",
    tabRequest = "Request",
    tabCollections = "Collections",
    tabEnvironments = "Environments",
    tabHistory = "History",
    tabStatus = "Status",
    noEnvironment = "No Environment",
    save = "Save",
    send = "Send",
    paramsTab = "Params",
    headersTab = "Headers",
    bodyTab = "Body",
    authTab = "Auth",
    prettify = "Prettify",
    noBody = "This request does not include a body.",
    timeLabel = "Time",
    sizeLabel = "Size",
    snapshot = "Snapshot",
    connectionFailed = "Connection Failed",
    saveRequestTitle = "Save Request",
    requestNameLabel = "Request Name",
    saveToCollection = "Save to Collection:",
    cancel = "Cancel",
    snapshotTitle = "Save Response Snapshot",
    snapshotSubtitle = "Save this response state to compare before/after deploys.",
    collectionsTitle = "Collections",
    importPostman = "Import Postman",
    exportPostman = "Export Postman",
    newCollection = "New Collection",
    noCollections = "No Collections Yet",
    noCollectionsSubtitle = "Create one or import a Postman collection JSON.",
    collectionNameLabel = "Collection Name (e.g. Auth Service)",
    collectionDescLabel = "Description (optional)",
    create = "Create",
    loadSamplePostman = "Load Sample Postman Collection",
    importBtn = "Import",
    copied = "Copied!",
    copyJson = "Copy JSON",
    close = "Close",
    vaultUnlocked = "Secrets Vault: Unlocked",
    vaultProtected = "Secrets Vault: Protected",
    vaultVisibleNotice = "Sensitive API tokens are visible",
    vaultLockedNotice = "Face ID / Biometric / PIN locked",
    lock = "Lock",
    unlock = "Unlock",
    selectActiveEnv = "Select Active Environment",
    envVariablesTitle = "Variables",
    envUsageNotice = "Use as {{variableName}} in URLs, headers, or body",
    newEnvironmentTitle = "New Environment",
    envNameLabel = "Environment Name (e.g. QA, Staging)",
    authenticate = "Authenticate",
    masterPinLabel = "Master PIN (or tap Authenticate)",
    bioPrompt = "Authenticate using device biometrics or dev master PIN (use '1234' or tap Authenticate) to reveal stored API keys and tokens.",
    requestHistoryTab = "Request History",
    compareTab = "Side-by-Side Compare",
    recentExecutions = "Recent Executions",
    clearAll = "Clear All",
    noHistory = "No request history yet",
    noHistorySubtitle = "Send requests in the Request Builder to log them here.",
    openInBuilder = "Open in Builder",
    setCompareA = "Set Compare A",
    setCompareB = "Set Compare B",
    slotA = "Baseline (A)",
    slotB = "Compare Target (B)",
    diffOverview = "Diff Metrics Overview",
    statusCode = "Status Code",
    latencyDelta = "Latency Delta",
    payloadDelta = "Payload Delta",
    responsePayloads = "Response Payloads",
    baselineOutput = "Baseline (A) Output",
    targetOutput = "Target (B) Output",
    compareHint = "Select both Compare A and Compare B from your Request History to compare before & after responses.",
    statusPageTitle = "API Health Status Page",
    allOperational = "All endpoints operational",
    endpointsOperational = "endpoints operational",
    pingAll = "Ping All",
    noMonitored = "No Monitored Endpoints",
    noMonitoredSubtitle = "Add critical API routes to check health with a single tap.",
    addEndpointTitle = "Add Endpoint to Status Page",
    serviceNameLabel = "Service Name (e.g. Auth Service)",
    healthCheckUrlLabel = "Health Check URL",
    expectedStatusLabel = "Expected Status Code (usually 200)",
    addEndpointBtn = "Add Endpoint",
    themeDark = "Dark Mode",
    themeLight = "Light Mode",
    language = "Language"
)

val RussianStrings = AppStrings(
    appTitle = "API Playground",
    tabRequest = "Запрос",
    tabCollections = "Коллекции",
    tabEnvironments = "Окружения",
    tabHistory = "История",
    tabStatus = "Статус",
    noEnvironment = "Без окружения",
    save = "Сохранить",
    send = "Отправить",
    paramsTab = "Параметры",
    headersTab = "Заголовки",
    bodyTab = "Тело",
    authTab = "Авторизация",
    prettify = "Форматировать",
    noBody = "Этот запрос не содержит тела.",
    timeLabel = "Время",
    sizeLabel = "Размер",
    snapshot = "Снимок",
    connectionFailed = "Ошибка соединения",
    saveRequestTitle = "Сохранить запрос",
    requestNameLabel = "Имя запроса",
    saveToCollection = "Сохранить в коллекцию:",
    cancel = "Отмена",
    snapshotTitle = "Сохранить снимок ответа",
    snapshotSubtitle = "Сохраните состояние ответа для сравнения до/после деплоя.",
    collectionsTitle = "Коллекции",
    importPostman = "Импорт Postman",
    exportPostman = "Экспорт Postman",
    newCollection = "Новая коллекция",
    noCollections = "Нет коллекций",
    noCollectionsSubtitle = "Создайте новую или импортируйте JSON коллекции Postman.",
    collectionNameLabel = "Имя коллекции (напр., Auth Service)",
    collectionDescLabel = "Описание (необязательно)",
    create = "Создать",
    loadSamplePostman = "Загрузить пример коллекции Postman",
    importBtn = "Импортировать",
    copied = "Скопировано!",
    copyJson = "Копировать JSON",
    close = "Закрыть",
    vaultUnlocked = "Сейф секретов: Разблокирован",
    vaultProtected = "Сейф секретов: Защищен",
    vaultVisibleNotice = "Секретные API ключи и токены видны",
    vaultLockedNotice = "Заблокировано биометрией / PIN-кодом",
    lock = "Заблокировать",
    unlock = "Разблокировать",
    selectActiveEnv = "Выберите активное окружение",
    envVariablesTitle = "Переменные",
    envUsageNotice = "Используйте как {{variableName}} в URL, заголовках или теле",
    newEnvironmentTitle = "Новое окружение",
    envNameLabel = "Имя окружения (напр., QA, Staging)",
    authenticate = "Аутентификация",
    masterPinLabel = "Мастер-PIN (или нажмите Аутентификация)",
    bioPrompt = "Подтвердите личность с помощью биометрии или PIN-кода (введите '1234' или нажмите кнопку) для доступа к секретам.",
    requestHistoryTab = "История запросов",
    compareTab = "Сравнение бок о бок",
    recentExecutions = "Недавние выполнения",
    clearAll = "Очистить всё",
    noHistory = "История запросов пуста",
    noHistorySubtitle = "Отправляйте запросы в конструкторе, чтобы видеть их здесь.",
    openInBuilder = "Открыть в конструкторе",
    setCompareA = "Выбрать как А",
    setCompareB = "Выбрать как Б",
    slotA = "Базовый снимок (А)",
    slotB = "Сравниваемый (Б)",
    diffOverview = "Обзор различий",
    statusCode = "Код статуса",
    latencyDelta = "Разница задержки",
    payloadDelta = "Разница размера",
    responsePayloads = "Тела ответов",
    baselineOutput = "Вывод базового (А)",
    targetOutput = "Вывод сравниваемого (Б)",
    compareHint = "Выберите оба запроса (А и Б) из истории для визуального сравнения результатов.",
    statusPageTitle = "Мониторинг здоровья API",
    allOperational = "Все эндпоинты работают",
    endpointsOperational = "эндпоинтов работают",
    pingAll = "Проверить все",
    noMonitored = "Нет отслеживаемых эндпоинтов",
    noMonitoredSubtitle = "Добавьте критические маршруты API для быстрой проверки.",
    addEndpointTitle = "Добавить эндпоинт в мониторинг",
    serviceNameLabel = "Имя сервиса (напр., Auth Service)",
    healthCheckUrlLabel = "URL проверки здоровья",
    expectedStatusLabel = "Ожидаемый статус-код (обычно 200)",
    addEndpointBtn = "Добавить эндпоинт",
    themeDark = "Тёмная тема",
    themeLight = "Светлая тема",
    language = "Язык"
)

val UzbekStrings = AppStrings(
    appTitle = "API Playground",
    tabRequest = "So'rov",
    tabCollections = "Kolleksiyalar",
    tabEnvironments = "Muhitlar",
    tabHistory = "Tarix",
    tabStatus = "Holat",
    noEnvironment = "Muhit tanlanmagan",
    save = "Saqlash",
    send = "Yuborish",
    paramsTab = "Parametrlar",
    headersTab = "Sarlavhalar",
    bodyTab = "Tana (Body)",
    authTab = "Autentifikatsiya",
    prettify = "Tartiblash",
    noBody = "Bu so'rovda tana mavjud emas.",
    timeLabel = "Vaqt",
    sizeLabel = "Hajm",
    snapshot = "Nusxa",
    connectionFailed = "Ulanishda xatolik",
    saveRequestTitle = "So'rovni saqlash",
    requestNameLabel = "So'rov nomi",
    saveToCollection = "Kolleksiyaga saqlash:",
    cancel = "Bekor qilish",
    snapshotTitle = "Javob nusxasini saqlash",
    snapshotSubtitle = "Deploydan oldingi va keyingi holatni taqqoslash uchun saqlang.",
    collectionsTitle = "Kolleksiyalar",
    importPostman = "Postman import",
    exportPostman = "Postman eksport",
    newCollection = "Yangi kolleksiya",
    noCollections = "Hozircha kolleksiyalar yo'q",
    noCollectionsSubtitle = "Yangi kolleksiya yarating yoki Postman JSON faylini import qiling.",
    collectionNameLabel = "Kolleksiya nomi (masalan, Auth Service)",
    collectionDescLabel = "Tavsif (ixtiyoriy)",
    create = "Yaratish",
    loadSamplePostman = "Namuna Postman to'plamini yuklash",
    importBtn = "Import qilish",
    copied = "Nusxalandi!",
    copyJson = "JSON nusxalash",
    close = "Yopish",
    vaultUnlocked = "Maxfiy Seyf: Ochiq",
    vaultProtected = "Maxfiy Seyf: Himoyalangan",
    vaultVisibleNotice = "Maxfiy API kalitlari va tokenlar ko'rinmoqda",
    vaultLockedNotice = "Biometriya yoki PIN bilan qulflangan",
    lock = "Qulflash",
    unlock = "Ochish",
    selectActiveEnv = "Faol muhitni tanlang",
    envVariablesTitle = "O'zgaruvchilar",
    envUsageNotice = "URL, sarlavhalar yoki tanada {{ozgaruvchi}} ko'rinishida ishlating",
    newEnvironmentTitle = "Yangi muhit",
    envNameLabel = "Muhit nomi (masalan, QA, Staging)",
    authenticate = "Tasdiqlash",
    masterPinLabel = "Asosiy PIN (yoki Tasdiqlashni bosing)",
    bioPrompt = "Maxfiy kalitlarni ko'rish uchun biometriya yoki dev PIN kodidan ('1234') foydalaning.",
    requestHistoryTab = "So'rovlar tarixi",
    compareTab = "Yonma-yon taqqoslash",
    recentExecutions = "So'nggi bajarilganlar",
    clearAll = "Barchasini tozalash",
    noHistory = "So'rovlar tarixi bo'sh",
    noHistorySubtitle = "So'rovlarni konstruktordan yuboring, ular bu yerda saqlanadi.",
    openInBuilder = "Konstruktorda ochish",
    setCompareA = "A sifatida tanlash",
    setCompareB = "B sifatida tanlash",
    slotA = "Asosiy holat (A)",
    slotB = "Taqqoslash nishoni (B)",
    diffOverview = "Taqqoslash xulosasi",
    statusCode = "Status kodi",
    latencyDelta = "Kechikish farqi",
    payloadDelta = "Hajm farqi",
    responsePayloads = "Javob natijalari",
    baselineOutput = "Asosiy (A) natijasi",
    targetOutput = "Nishon (B) natijasi",
    compareHint = "Tarixdan ikkita so'rovni (A va B) tanlab, natijalarni yonma-yon solishtiring.",
    statusPageTitle = "API Holat Monitoringi",
    allOperational = "Barcha endpointlar ishlamoqda",
    endpointsOperational = "ta endpoint ishlamoqda",
    pingAll = "Barchasini tekshirish",
    noMonitored = "Kuzatilayotgan endpointlar yo'q",
    noMonitoredSubtitle = "Bir tegishda tez tekshirish uchun API marshrutlarini qo'shing.",
    addEndpointTitle = "Monitoringga endpoint qo'shish",
    serviceNameLabel = "Xizmat nomi (masalan, Auth Service)",
    healthCheckUrlLabel = "Tekshirish manzili (Health Check URL)",
    expectedStatusLabel = "Kutilayotgan status kodi (odatda 200)",
    addEndpointBtn = "Qo'shish",
    themeDark = "Tungi rejim",
    themeLight = "Kunduzgi rejim",
    language = "Til"
)

fun getStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.RUSSIAN -> RussianStrings
        AppLanguage.UZBEK -> UzbekStrings
    }
}
